# Generated by Django 5.1.4 on 2024-12-11 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("santa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="created_by",
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
