# Generated by Django 5.1.4 on 2024-12-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("santa", "0002_room_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="created_by",
            field=models.CharField(max_length=100),
        ),
    ]
