# Generated by Django 5.1.4 on 2024-12-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("santa", "0003_alter_room_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="room",
        ),
        migrations.AddField(
            model_name="participant",
            name="address",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="participant",
            name="budget",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="participant",
            name="hobby",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="participant",
            name="isPresentInBangalore",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="participant",
            name="phone",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="participant",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="participant",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
